name: CI

on:
  push:
    branches: [ main, add_tests ]
  pull_request:
    branches: [ main, add_tests ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install uv
        uv sync --test
    - name: Run tests
      run: uv run pytest 