name: CI

on:
  push:
    branches: [ main, add_tests ]
  pull_request:
    branches: [ main, add_tests ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install uv
        uv sync --extra test
    - name: Run tests with coverage
      run: uv run pytest --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

    - name: Generate coverage badge
      if: github.ref == 'refs/heads/main'
      run: |
        # Extract coverage percentage from XML
        COVERAGE=$(python -c "
        import xml.etree.ElementTree as ET
        tree = ET.parse('coverage.xml')
        root = tree.getroot()
        coverage = float(root.attrib['line-rate']) * 100
        print(f'{coverage:.2f}')
        ")
        
        # Create shields.io badge URL
        BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
        
        # Update README.md with new badge URL
        sed -i "s|https://img.shields.io/badge/coverage-[0-9.]*%25-brightgreen|${BADGE_URL}|g" README.md
        
        # Commit and push if changes were made
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Update coverage badge to ${COVERAGE}%"
        git push origin HEAD:main 